version: '2'
services:
    janmicro-app:
        image: janmicro
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://janmicro-mysql:3306/janmicro?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    janmicro-mysql:
        extends:
            file: mysql.yml
            service: janmicro-mysql
